# Generated by Django 2.2 on 2020-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20200916_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
