# Generated by Django 2.2 on 2020-09-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200916_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
