# Generated by Django 3.1.2 on 2020-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20201019_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
