# Generated by Django 3.1.2 on 2020-10-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_content_message_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Message_Board',
        ),
    ]
