# Generated by Django 3.1.2 on 2020-10-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_auto_20201028_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cAddr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
