# Generated by Django 3.1.2 on 2020-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_auto_20201028_0402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
